[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# environment variables:
[context."branch-deploy.dev".environment]
  NEXTAUTH_URL = "https://dev--work-e.netlify.app"

[context."branch-deploy.stage".environment]
  NEXTAUTH_URL = "https://stage--work-e.netlify.app"

[context."branch-deploy.dialog".environment]
  NEXTAUTH_URL = "https://dialog--work-e.netlify.app"

[context."branch-deploy.prev-1".environment]
  NEXTAUTH_URL = "https://prev-1--work-e.netlify.app"

[context."branch-deploy.prev-2".environment]
  NEXTAUTH_URL = "https://prev-2--work-e.netlify.app"

[context."branch-deploy.prev-3".environment]
  NEXTAUTH_URL = "https://prev-3--work-e.netlify.app"